### ISSUE TITLE
Technology Search - by default no technologies are returned

### ISSUE THREAD

**Issue by michalsi** [gpimblott/TechRadar#59]
When you go to https://k-tech-radar.herokuapp.com/technology/search
The list displayed is empty

You can type something to search box to view matching technologies
Also if you just hit enter in empty search box the whole list is displayed - which should be shown by default

**Comment by gpimblott** [comment]
Also focus isn't on the search box by default :( 

Recommend list is displayed by default and search box has focus on page load 👍

**Comment by gpimblott** [comment]
Technology search now displays all results - server side paging still needs to be implmented
