### ISSUE TITLE
To enable roll-out to a wider audience a 'sign-up' process is required

### ISSUE THREAD

**Issue by gpimblott** [gpimblott/TechRadar#71]
Users need to be able to register for an account and set their password - Accounts either manually approved or automated email approved addressed

**Comment by adrianz-kainos** [comment]
@gpimblott  How about we add manual approval first and then work on
automated approval for email accounts ending in "@kainos.com" (plus an activation link sent via email)? What is your vision? :)

**Comment by gpimblott** [comment]
I was thinking exactly the same.  Manual approval first e.g. create disabled, then email link validation later...much later.  It would be handy if the admin was emailed when an account was created, to know to go and activate the account

**Comment by adrianz-kainos** [comment]
Forgot to ask: @gpimblott could you assign me to this task, to let other contributors know that I am working on it?
