### ISSUE TITLE
Markdown for comments

### ISSUE THREAD

**Issue by p3t3rc** [gpimblott/TechRadar#84]
Whitespace formatting is lost when you submit which discourages longer comments. 

Support markdown for comments to allow longer comments to be more readable.

**Comment by gpimblott** [comment]
<img width="765" alt="Screenshot 2019-05-02 at 22 32 08" src="https://user-images.githubusercontent.com/2563249/57108408-8b9eb980-6d2a-11e9-8c29-e07db80dae66.png">
 Markdown for comments added to Open Source version of the codebase
